# Generated by Django 5.1 on 2024-09-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_message_notification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
